In [3]:
import numpy as np

In [ ]:
### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third
# column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr1 = np.random.randint(1, 21, size = (5, 5))

arr1[:, 2] = 1
# print(arr1)

arr2     = np.arange(1, 17).reshape(4, 4)
arr2_len = len(arr2)
indexes = list(range(arr2_len))

print(arr2)
print()

for i in indexes:
    for j in indexes:
        if j == i:
            arr2[i, j] = 0
            pass
        if j == (arr2_len - 1) - i:
            arr2[i, j] = 0

print(arr2)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 0  2  3  0]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [ 0 14 15  0]]


In [134]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th
# rows and 2nd to 4th columns.
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr3 = np.arange(1, 37).reshape(6, 6)
# print(arr3[2:5, 1:4])

arr4 = np.arange(1, 26).reshape(5, 5)

# arr4 = np.random.randint(0, 10, size = (5, 5)) # unresolved by usual means
border_elements = []
arr4_len        = len(arr4)

print(arr4)

for (outer_index, inner_arr) in enumerate(arr4):
    for (inner_index, value) in enumerate(inner_arr):
        if outer_index == 0 or outer_index == (arr4_len - 1):
            border_elements.append(arr4[outer_index, inner_index])
        else:
            if inner_index == 0 or inner_index == (arr4_len - 1):
                border_elements.append(arr4[outer_index, inner_index])

ndarr_border_elements = np.array(border_elements)
print(ndarr_border_elements)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  2  3  4  5  6 10 11 15 16 20 21 22 23 24 25]


In [138]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction,
# multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr5 = np.random.randint(0, 10, size = (3, 4))
arr6 = np.random.randint(0, 10, size = (3, 4))

# # addition
# print(arr5)
# print()
# print(arr6)
# print()
# print(arr5 + arr6)

# # subtraction
# print(arr5)
# print()
# print(arr6)
# print()
# print(arr5 - arr6)

# # multiplication
# print(arr5)
# print()
# print(arr6)
# print()
# print(arr5 * arr6)

# # division
# print(arr5)
# print()
# print(arr6)
# print()
# print(arr5 / arr6)

arr6 = np.random.randint(1, 10, size = (4, 4))
print(arr6)
print()
print(np.sum(arr6))

[[1 9 3 1]
 [1 8 7 4]
 [3 6 3 9]
 [4 2 5 7]]

73


In [142]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation,
# and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a
# mean of 0 and a standard deviation of 1).

arr7 = np.random.randint(1, 10, size = (5, 5))
# print(np.mean(arr7))
# print(np.median(arr7))
# print(np.std(arr7))
# print(np.var(arr7))

arr8 = np.random.randint(1, 10, size = (3, 3))
print(arr8)
print()
arr8 = (arr8 - np.mean(arr8)) / np.std(arr8)
print(arr8)

[[9 2 1]
 [8 9 9]
 [6 8 3]]

[[ 0.94064699 -1.33861302 -1.66422159]
 [ 0.61503841  0.94064699  0.94064699]
 [-0.03617873  0.61503841 -1.01300445]]


In [147]:
### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the
# 2D array using broadcasting.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column
# of the 2D array using broadcasting.

arr9       = np.random.randint(1, 10, size = (3, 3))
base_list  = [1, 2, 3]
arr1_1d    = np.array(base_list)
arr9_broad = arr9 + arr1_1d

print(arr9_broad)

arr10   = np.random.randint(1, 10, size = (4, 4))
base_list.append(4)
arr1_2d = np.array(base_list)

arr10_broad = arr10 + arr1_2d

print(arr10_broad)


[[ 5 11  5]
 [ 9 10  8]
 [10  7  4]]
[[ 2  4  9  5]
 [ 3  7  8 13]
 [ 7 10  6  5]
 [10  5  5  6]]


In [ ]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.