In [1]:
import numpy as np

In [2]:
### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third
# column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr1 = np.random.randint(1, 21, size = (5, 5))

arr1[:, 2] = 1
# print(arr1)

arr2     = np.arange(1, 17).reshape(4, 4)
arr2_len = len(arr2)
indexes = list(range(arr2_len))

print(arr2)
print()

for i in indexes:
    for j in indexes:
        if j == i:
            arr2[i, j] = 0
            pass
        if j == (arr2_len - 1) - i:
            arr2[i, j] = 0

print(arr2)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 0  2  3  0]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [ 0 14 15  0]]


In [3]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th
# rows and 2nd to 4th columns.
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr3 = np.arange(1, 37).reshape(6, 6)
# print(arr3[2:5, 1:4])

arr4 = np.arange(1, 26).reshape(5, 5)

# arr4 = np.random.randint(0, 10, size = (5, 5)) # unresolved by usual means
border_elements = []
arr4_len        = len(arr4)

print(arr4)

for (outer_index, inner_arr) in enumerate(arr4):
    for (inner_index, value) in enumerate(inner_arr):
        if outer_index == 0 or outer_index == (arr4_len - 1):
            border_elements.append(arr4[outer_index, inner_index])
        else:
            if inner_index == 0 or inner_index == (arr4_len - 1):
                border_elements.append(arr4[outer_index, inner_index])

ndarr_border_elements = np.array(border_elements)
print(ndarr_border_elements)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  2  3  4  5  6 10 11 15 16 20 21 22 23 24 25]


In [4]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction,
# multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr5 = np.random.randint(0, 10, size = (3, 4))
arr6 = np.random.randint(0, 10, size = (3, 4))

# # addition
# print(arr5)
# print()
# print(arr6)
# print()
# print(arr5 + arr6)

# # subtraction
# print(arr5)
# print()
# print(arr6)
# print()
# print(arr5 - arr6)

# # multiplication
# print(arr5)
# print()
# print(arr6)
# print()
# print(arr5 * arr6)

# # division
# print(arr5)
# print()
# print(arr6)
# print()
# print(arr5 / arr6)

arr6 = np.random.randint(1, 10, size = (4, 4))
print(arr6)
print()
print(np.sum(arr6))

[[6 9 1 4]
 [8 2 7 5]
 [8 9 4 4]
 [9 9 6 8]]

99


In [5]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation,
# and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a
# mean of 0 and a standard deviation of 1).

arr7 = np.random.randint(1, 10, size = (5, 5))
# print(np.mean(arr7))
# print(np.median(arr7))
# print(np.std(arr7))
# print(np.var(arr7))

arr8 = np.random.randint(1, 10, size = (3, 3))
print(arr8)
print()
arr8 = (arr8 - np.mean(arr8)) / np.std(arr8)
print(arr8)

[[2 4 1]
 [5 1 7]
 [6 1 2]]

[[-0.5555839   0.35355339 -1.01015254]
 [ 0.80812204 -1.01015254  1.71725933]
 [ 1.26269068 -1.01015254 -0.5555839 ]]


In [6]:
### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the
# 2D array using broadcasting.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column
# of the 2D array using broadcasting.

arr9       = np.random.randint(1, 10, size = (3, 3))
base_list  = [1, 2, 3]
arr1_1d    = np.array(base_list)
arr9_broad = arr9 + arr1_1d

print(arr9_broad)

arr10   = np.random.randint(1, 10, size = (4, 4))
base_list.append(4)
arr1_2d = np.array(base_list)

arr10_broad = arr10 + arr1_2d

print(arr10_broad)


[[ 8  7 10]
 [ 4  4  5]
 [10  7 12]]
[[ 4 10 12 12]
 [ 7  9  4 12]
 [ 9  9  6 10]
 [ 2  3 11 10]]


In [7]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

arr11           = np.random.randint(1, 20, size = (3, 3))
det_arr11       = np.linalg.det(arr1)
inverse_arr11   = np.linalg.inv(arr11)
eigen_val_arr11 = np.linalg.eig(arr11).eigenvalues

print('determinant', det_arr11)
print('inverse', inverse_arr11)
print('eigenvalues', eigen_val_arr11)

arr12      = np.random.randint(1, 20, size = (2, 3))
arr13      = np.random.randint(1, 20, size = (3, 2))
matrix_mul = np.dot(arr12, arr13)

print('matrix multiplication', matrix_mul)


determinant -5353.0
inverse [[ 0.05384615  0.3        -0.31538462]
 [-0.07307692 -0.05        0.14230769]
 [ 0.09038462 -0.175       0.11346154]]
eigenvalues [36.72454422+0.j          0.63772789+3.70847285j  0.63772789-3.70847285j]
matrix multiplication [[288 123]
 [370 154]]


In [8]:
### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

arr14 = np.random.randint(1, 10, size = (3, 3))
arr14.reshape(1, 9)
arr14.reshape(9, 1)

arr15 = np.random.randint(1, 26, size = (5, 5))
arr15 = np.ndarray.flatten(arr15)
arr15 = arr15.reshape(5, 5)
print(arr15)


[[13 14  9 23 23]
 [ 7 17  2 19 15]
 [21  2  5 15 10]
 [14  6 10  9 12]
 [16 13 14 10 17]]


In [9]:
### Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the
# corners of the array.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater
# than 10 to 10.

arr16 = np.random.randint(1, 26, size = (5, 5))
print(arr16[[0, 0, -1, -1], [0, -1, 0, -1]])
print()
arr17 = np.random.randint(1, 26, size = (4, 4))
arr17[arr17 > 10] = 0
print(arr17)


[21 10 19 14]

[[0 0 3 0]
 [0 0 0 0]
 [5 0 0 4]
 [0 0 0 6]]


In [10]:
### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float).
# Add some data and sort the array by age.
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean
# distance between each pair of points.

dt    = np.dtype([('name', (np.str_, 10)), ('age', np.int32), ('weight', np.float32)])
arr18 = np.array([('Person 1', 40, 100.50), ('Person 2', 35, 80.75)], dtype = dt)
print(arr18)
print()
arr18 = np.sort(arr18, order = 'age')
print(arr18)
print()
dt_1  = np.dtype([('x', np.int32), ('y', np.int32)])
arr19 = np.array([(10, 20), (30, 40)], dtype = dt_1)
print()
p1 = np.array(list(arr19[0]))
p2 = np.array(list(arr19[1]))

euclidean_distance = np.linalg.norm(p1 - p2)
print(euclidean_distance)

[('Person 1', 40, 100.5 ) ('Person 2', 35,  80.75)]

[('Person 2', 35,  80.75) ('Person 1', 40, 100.5 )]


28.284271247461902


In [28]:
### Assignment 10: Masked Arrays

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

arr19                = np.random.randint(1, 20, size = (4, 4))
greater_than_10_mask = arr19 > 10
sum_unmasked         = arr19[~greater_than_10_mask].sum()

# print(sum_unmasked)
# print()

arr20 = np.random.randint(1, 20, size = (3, 3))

row_indexes_m    = []
column_indexes_m = []
arr20_len        = len(arr20)

row_indexes_unm    = []
column_indexes_unm = []

for (i, value_row) in enumerate(arr20):
    for (j, value_col) in enumerate(value_row):
        if j == i or j == (arr20_len - 1) - i:
            row_indexes_m.append(i)
            column_indexes_m.append(j)
        else:
            row_indexes_unm.append(i)
            column_indexes_unm.append(j)

print(arr20)
print()
print(arr20[row_indexes_unm, column_indexes_unm])
arr20[row_indexes_unm, column_indexes_unm] = arr20[row_indexes_m, column_indexes_m].mean()
print(arr20[row_indexes_unm, column_indexes_unm])

[[14 15 11]
 [ 6  9 14]
 [13 14 17]]

[15  6 14 14]
[12 12 12 12]
